# Generated by Django 4.0.2 on 2022-04-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ImageUrl',
            field=models.CharField(default='https://www.publicdomainpictures.net/pictures/280000/velka/not-found-image-15383864787lu.jpg', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='ImageUrl',
            field=models.CharField(default='https://www.publicdomainpictures.net/pictures/280000/velka/not-found-image-15383864787lu.jpg', max_length=1000),
            preserve_default=False,
        ),
    ]
