# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: ITG_docker_build_only

on:
  push:
    branches:
      - itg
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: itg

    # run django tests
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pipenv wheel
        ls -lah
        PIPENV_DOTENV_LOCATION=./local.env pipenv install --deploy
    
    - name: Run Tests
      run: |
        pwd && ls -lah
        cd backend
        pwd && ls -lah
        PIPENV_DOTENV_LOCATION=../local.env pipenv run printenv
        PIPENV_DOTENV_LOCATION=../local.env pipenv run pwd && ls -lah
        PIPENV_DOTENV_LOCATION=../local.env pipenv run python manage.py test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ece651foodie.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_53746dbef1fb44f585621ca2289898c8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_69f3a7e96e3548e8baeadc6df7dc2ca7 }}

    - name: Build and push backend container image to registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ece651foodie.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_53746dbef1fb44f585621ca2289898c8 }}/ece651_backend:dev
        file: ./Dockerfile

    - name: Build and push frontend container image to registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ece651foodie.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_53746dbef1fb44f585621ca2289898c8 }}/ece651_frontend:dev
        file: ./frontend/Dockerfile
